---
title: Matthew Bischoff
timezone: America/New_York
collections:
  appearances:
    title: Appearances
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/matthew.jpg"
permalink: "/:title/"
url: https://matthewbischoff.com
paginate: 3
baseurl: https://matthewbischoff.com/
author:
  name: Matthew Bischoff
  url: https://twitter.com/mb
  email: mb@matthewbischoff.com
  twitter: mb
description: Hey, I’m <a href="/about/">Matt</a>. I write software in New York.
logo: "/assets/matthew.jpg"
version: 0.2
github:
  repo: https://github.com/mattbischoff/matthewbischoff.com
license:
  text: Some rights reserved
  url: http://creativecommons.org/licenses/by-sa/4.0/
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed
- jekyll-redirect-from
twitter:
  username: mb
facebook:
  publisher: https://www.facebook.com/matthewbischoff
  admins: https://www.facebook.com/matthewbischoff
google_site_verification: XK_j6lkDAd8qOhIn4-2eS2BIJuQyRp4D_gxjpR65wUM
sass:
  sass_dir: _sass
  style: compressed
