# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            Matthew Bischoff
url:              https://matthewbischoff.com
paginate:         3
baseurl:          /
author:
  name:           Matthew Bischoff
  url:            https://twitter.com/mb
  email:          mb@matthewbischoff.com
tagline: 		  "Hey, I’m Matt. Nice to meet you."

# Custom Variables
version:          0.1
github:
  repo:           https://github.com/mattbischoff/matthewbischoff.com

gems:
  - jekyll-sitemap