---
title: Matthew Bischoff
timezone: America/New_York
permalink: "/:title/"
url: http://matthewbischoff.com
paginate: 3
baseurl: "/"
author:
  name: Matthew Bischoff
  url: https://twitter.com/mb
  email: mb@matthewbischoff.com
description: Hey, I’m <a href="/about/">Matt</a>. I write software in New York.
version: 0.2
github:
  repo: https://github.com/mattbischoff/matthewbischoff.com
license:
  text: Some rights reserved
  url: http://creativecommons.org/licenses/by-sa/4.0/
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist


collections:
  appearances:
    title: Appearances
    output: true
  posts:
    title: Posts
    output: true
  talks:
    title: Talks
    output: true
  uploads:
    title: Uploads
    output: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
