# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            Matthew Bischoff
url:              https://matthewbischoff.com
paginate:         3
baseurl:          /
author:
  name:           Matthew Bischoff
  url:            https://twitter.com/mb
  email:          mb@matthewbischoff.com
bio: 		  	  "Hey, I’m Matt. I make things in New York at <a href=\"http://lickability.com\">Lickabilty</a> and <a href=\"http://tumblr.com\">Tumblr</a>."

# Custom Variables
version:          0.1
github:
  repo:           https://github.com/mattbischoff/matthewbischoff.com

gems:
  - jekyll-sitemap