# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            Matthew Bischoff
url:              http://matthewbischoff.com
paginate:         3
baseurl:          /
author:
  name:           Matthew Bischoff
  url:            https://twitter.com/mb
  email:          mb@matthewbischoff.com
description:      "Hello, I’m <a href=\"/about/\">Matt</a>. I make apps in New York at <a href=\"http://lickability.com\">Lickability</a>."

# Custom Variables
version:          0.1
github:
  repo:           https://github.com/mattbischoff/matthewbischoff.com
license:
  text:           "Some rights reserved"
  url:            http://creativecommons.org/licenses/by-sa/4.0/

gems:
  - jekyll-sitemap
 
